In [1]:
import pandas as pd
import numpy as np


In [2]:
path = r"C:\Users\hk3to\OneDrive\Documents\Data_Talks\Machine learning\work\Assignment\homework_5\bank\bank-full.csv"

In [3]:
path

'C:\\Users\\hk3to\\OneDrive\\Documents\\Data_Talks\\Machine learning\\work\\Assignment\\homework_5\\bank\\bank-full.csv'

In [31]:
import pipenv
from sklearn.linear_model import LogisticRegression

In [32]:
!pipenv --version

pipenv, version 2024.0.1


In [6]:
!pipenv install scikit-learn==1.5.2

Installing scikit-learn==1.5.2...
Resolving scikit-learn==1.5.2...
[    ] Installing...
Added scikit-learn to Pipfile's [packages] ...
[    ] Installing scikit-learn...
Installation Succeeded
[    ] Installing scikit-learn...
[    ] Installing scikit-learn...

Building requirements...
[    ] Locking packages...
Resolving dependencies...
[    ] Locking packages...
[=   ] Locking packages...
[==  ] Locking packages...
[=== ] Locking packages...
[ ===] Locking packages...
[  ==] Locking packages...
[   =] Locking packages...
[   =] Locking packages...
[  ==] Locking packages...
[ ===] Locking packages...
[====] Locking packages...
[=== ] Locking packages...
[==  ] Locking packages...
[    ] Locking packages...
[=   ] Locking packages...
[==  ] Locking packages...
[=== ] Locking packages...
[ ===] Locking packages...
[  ==] Locking packages...
[    ] Locking packages...
[   =] Locking packages...
[  ==] Locking packages...
[ ===] Locking packages...
[====] Locking packages...
[=== ] Lockin

Pipfile.lock not found, creating...
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (adb15e5c5a21f13e221698df1bb36dc8d3bee16bb778fdfcad74b126616757b9)!



[   =] Locking packages...
[    ] Locking packages...
[   =] Locking packages...
[  ==] Locking packages...
[====] Locking packages...
[=== ] Locking packages...
[==  ] Locking packages...
[=   ] Locking packages...
[    ] Locking packages...
[=   ] Locking packages...
[=== ] Locking packages...
[ ===] Locking packages...
[  ==] Locking packages...
[   =] Locking packages...
[    ] Locking packages...
[   =] Locking packages...
[ ===] Locking packages...
[====] Locking packages...
[=== ] Locking packages...
[==  ] Locking packages...
[=   ] Locking packages...
[=   ] Locking packages...
[==  ] Locking packages...
[=== ] Locking packages...
[ ===] Locking packages...
[  ==] Locking packages...
[   =] Locking packages...
[   =] Locking packages...
[  ==] Locking packages...
[ ===] Locking packages...
[====] Locking packages...
[=== ] Locking packages...
[==  ] Locking packages...
[    ] Locking packages...
[=   ] Locking packages...
[==  ] Locking packages...
[=== ] Locking packages...


In [6]:
sckit_learn_hash ={      "scikit-learn": "sha256:03b6158efa3faaf1feea3faa884c840ebd61b6484167c711548fce208ea09445"
}

In [7]:
from sklearn.feature_extraction import DictVectorizer

In [8]:
df = pd.read_csv(path,delimiter=';')

In [9]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [10]:
features = ['job','duration','poutcome']
dicts = df[features].to_dict(orient='records')

In [11]:
dicts

[{'job': 'management', 'duration': 261, 'poutcome': 'unknown'},
 {'job': 'technician', 'duration': 151, 'poutcome': 'unknown'},
 {'job': 'entrepreneur', 'duration': 76, 'poutcome': 'unknown'},
 {'job': 'blue-collar', 'duration': 92, 'poutcome': 'unknown'},
 {'job': 'unknown', 'duration': 198, 'poutcome': 'unknown'},
 {'job': 'management', 'duration': 139, 'poutcome': 'unknown'},
 {'job': 'management', 'duration': 217, 'poutcome': 'unknown'},
 {'job': 'entrepreneur', 'duration': 380, 'poutcome': 'unknown'},
 {'job': 'retired', 'duration': 50, 'poutcome': 'unknown'},
 {'job': 'technician', 'duration': 55, 'poutcome': 'unknown'},
 {'job': 'admin.', 'duration': 222, 'poutcome': 'unknown'},
 {'job': 'admin.', 'duration': 137, 'poutcome': 'unknown'},
 {'job': 'technician', 'duration': 517, 'poutcome': 'unknown'},
 {'job': 'technician', 'duration': 71, 'poutcome': 'unknown'},
 {'job': 'services', 'duration': 174, 'poutcome': 'unknown'},
 {'job': 'retired', 'duration': 353, 'poutcome': 'unknow

In [12]:
dv = DictVectorizer(sparse=False)
X = dv.fit_transform(dicts)

In [13]:
y = df['y']

In [14]:
model = LogisticRegression().fit(X,y)

In [15]:
import pickle

In [15]:
with open('bank_model.bin','wb') as f_out:
    pickle.dump(model, f_out)

In [16]:
!wget 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework'


'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework': Scheme missing.


In [17]:
!wget 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework'


'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework': Scheme missing.


In [35]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework/model1.bin

--2024-10-27 17:21:18--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework/model1.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 850 [application/octet-stream]
Saving to: 'model1.bin.1'

     0K                                                       100% 16.1M=0s

2024-10-27 17:21:19 (16.1 MB/s) - 'model1.bin.1' saved [850/850]



In [38]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework/dv.bin

--2024-10-27 17:24:14--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/master/cohorts/2024/05-deployment/homework/dv.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 560 [application/octet-stream]
Saving to: 'dv.bin.1'

     0K                                                       100% 16.8M=0s

2024-10-27 17:24:18 (16.8 MB/s) - 'dv.bin.1' saved [560/560]



In [16]:
with open('model1.bin','rb') as f_in:
    model = pickle.load(f_in)

In [17]:
model

LogisticRegression(max_iter=250)

In [18]:
with open('dv.bin','rb') as dict_vect:
    dv = pickle.load(dict_vect)

In [19]:
dv

DictVectorizer(sparse=False)

In [16]:
client = {"job": "management", "duration": 400, "poutcome": "success"}

In [21]:
X = dv.transform(client)
X

array([[400.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   1.,   0.]])

In [22]:
model.predict(X)

array([1], dtype=int64)

In [23]:
prediction = model.predict_proba(

    X
)
prediction

array([[0.24090335, 0.75909665]])

In [24]:
round(list(prediction)[0][1],3)

0.759

In [17]:
import gunicorn
import waitress

In [26]:
client2 = client = {"job": "student", "duration": 280, "poutcome": "failure"}

In [27]:
client3 = {"job": "management", "duration": 400, "poutcome": "success"}

In [28]:
new = [client2,client3]

for clt in new:
    X = dv.transform(clt)
    prediction = list(model.predict_proba(X))
    print(prediction[0][1])

0.33480703475511053
0.7590966516879658


In [30]:
from docker import DockerClient

In [27]:
import docker

In [36]:
!docker image pull svizor/zoomcamp-model:3.11.5-slim

3.11.5-slim: Pulling from svizor/zoomcamp-model
a803e7c4b030: Pulling fs layer
bf3336e84c8e: Pulling fs layer
eb76b60fbb0c: Pulling fs layer
a2cee97f4fbd: Pulling fs layer
0358d4e17ae3: Pulling fs layer
fb37f8d7a667: Pulling fs layer
4e69cd59a5af: Pulling fs layer
a2cee97f4fbd: Waiting
0358d4e17ae3: Waiting
4e69cd59a5af: Waiting
fb37f8d7a667: Waiting
bf3336e84c8e: Verifying Checksum
bf3336e84c8e: Download complete
a2cee97f4fbd: Verifying Checksum
a2cee97f4fbd: Download complete
0358d4e17ae3: Verifying Checksum
0358d4e17ae3: Download complete
fb37f8d7a667: Verifying Checksum
fb37f8d7a667: Download complete
4e69cd59a5af: Verifying Checksum
4e69cd59a5af: Download complete
a803e7c4b030: Verifying Checksum
a803e7c4b030: Download complete
a803e7c4b030: Pull complete
bf3336e84c8e: Pull complete
eb76b60fbb0c: Verifying Checksum
eb76b60fbb0c: Download complete
eb76b60fbb0c: Pull complete
a2cee97f4fbd: Pull complete
0358d4e17ae3: Pull complete
fb37f8d7a667: Pull complete
4e69cd59a5af: Pull compl

In [44]:
path = r'C:\Users\hk3to\OneDrive\Documents\Data_Talks\Machine learning\work\Assignment\homework_5\model1.bin'

In [45]:
model7 = pickle.load(open(path,'rb'))

In [46]:
model7

LogisticRegression(max_iter=250)

In [47]:
client = {"job": "student", "duration": 280, "poutcome": "failure"}
model_path = r'C:\Users\hk3to\OneDrive\Documents\Data_Talks\Machine learning\work\Assignment\homework_5\model1.bin'
dv_path = r'C:\Users\hk3to\OneDrive\Documents\Data_Talks\Machine learning\work\Assignment\homework_5\dv.bin'
    
model = pickle.load(open(model_path,'rb'))
dv = pickle.load(open(dv_path,'rb'))
X = dv.transform(client)
prediction = list(model.predict_proba(X))
value = round(prediction[0][1],3)

In [48]:
value

0.335

In [20]:
import requests
import socket

In [21]:
hostname = socket.gethostname()
ip_addr = socket.gethostbyname(hostname)

In [22]:
ip_addr

'192.168.1.197'

In [24]:
with open('model1.bin','rb') as model_in:
    model = pickle.load(model_in)

In [25]:
model

LogisticRegression(max_iter=250)

In [26]:
url = f'http://{ip_addr}:8080/predict'
response = requests.post(url,json=client)
result = response.json()
result

{'prediction': 0.7590966516879658}

In [30]:
!docker run --rm python:svizor/zoomcamp-model

docker: invalid reference format.
See 'docker run --help'.


In [33]:
import os

In [ ]:
os.path.expanduser